### ISSUE TITLE
Finish Interpro Integration for domains

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/proteome-scout-3#16]
**Is your feature request related to a problem? Please describe.**
We are moving all domain information for proteins to be provided by InterPro. 

**Describe the solution you'd like**
We have already started this, but the new solution includes developing a new table that matches Interpro needs, such as keeping the Interpro Accession and short name as part of the information. Relative to old domain tables, we no longer need to keep track of prediction information. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Determine status in dev of domain table and protein viewer as it relates to domain table
- [ ] Determine status and testing of new fetching and domain table entries for protein records.
- [ ] Once integrated and unit tested, push the table/database updates to all databases and merge feature.
- [ ] Remove old domain table and the use of it by the protein viewer and database download and experimental annotation. 
- [ ] Include domain information as part of the database download and experimental annotations.
