### ISSUE TITLE
Migration of Protein Records and the effects on PTMs

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/proteome-scout-3#8]
**A new approach to systematically maintaining protein records**
As protein records in the underlying databases change, causing a non-exact record match between a UniProt and a current ProteomeScout record of that UniProt protein, we need to migrate the PTMs associated with that. In an analysis of the batch migration we will need to perform at this juncture, we identified that about 10% of human protein records are changed in some way (2,024 total proteins with PTMs). The majority have >85% similarity when judged by alignment -- only 257 records have significant deviation by that metric. We explored what happens when we consider the transfer of PTM information from existing compendia and experiments in order to come up with a solution, described here.

**Solution**
When a protein record is in need of replacing, the following flow chart suggests what should happen:
If current and new protein record are non-identical:
1. Test ability to migrate all PTM information. Successful migration occurs if in a pairwise alignment between an old and a new record a position in the new record can be identified by the following criteria: a) the amino acid at that position in the new record by alignment is identical (i.e. also a serine) and b) the tryptic fragment and the immediate +/-5amino acid window are unchanged. 
2. If all PTMs can be migrated, then the same protein id will be retained, the sequence and date updated, and the amino acid positions through alignment-based translation will be updated in relevant PTM tables. 
3. If not all PTMs can be migrated, and the PTMs are part of a non-compendia experiment and public experiment, then a new protein entry will be created, all PTM information that can be migrated to this new record will be, by update to relevant PTM tables of the protein.id and the sequence position translation to the new sequence. The current protein record that is retained in order to keep the record of the non-migratable PTM will be flagged as deprecated. 
4. New infrastructure to handle these changes will be added in the following way: A derivative experiment (for experiments affected by deprecated records) will be added that contains only PTMS linked to non-deprecated protein records and the database flat-file output will not include deprecated proteins or PTMs associated only with deprecated proteins.

**Describe alternatives you've considered**
We considered whether window/tryptic fragment errors in mapping should be considered an error in mapping or if the PTM records due to errors should be retained. We identified the best possible solution was to retain as much information about primary experiments as possible as a record that was identifiable/findable in the experiment area, but that these PTMs and records should not become part of the typical public record of PTMs if they cannot be accurately migrated. We also debated about tryptic versus window (motivated by typical MS mapping and the region of influence for recognition for most PTMs). Concern about how different cleavage enyzme use may suggest tryptic-windowing is an issue was considered, suggesting that generally both methods of windowing would be helpful to capture the confidence of a former record. 

#### Tasks
- [ ] Protein deprecation in a table as a flag should be added
- [ ] Database file generation to not include deprecated records added
- [ ] Protein search to not include deprecated records should be added 
- [ ] Other protein.id instances of use in ProteomeScout data generation and website identified and deprecation filter added.
- [ ] Code to perform flow chart of a protein record update implemented 
- [ ] Batch update to be performed for first major migration of records.

**Additional context**
We are still considering how to handle other records of note, including variants and isoforms.
