### ISSUE TITLE
Update the structure track to be color blind friendly 

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/proteome-scout-3#9]
**Feature: Make helix, strand, turn elements not green/red/purple**
In addition to looking terrible, the large amount of green and red are really not aesthetically pleasing, let's also make this color blind friendly. 
Screenshot example from [EGFR (P05533)](https://proteomescout.research.virginia.edu/proteins/52355/structure)
![Screenshot 2024-02-15 at 11 40 08 AM](https://github.com/NaegleLab/proteome-scout-3/assets/3899636/27d5e3a1-ac27-426c-b297-37cc640637fa)

**Describe the solution you'd like**
helix: #785EF0
strand: #FFB000
turn: #DC267F

**Describe alternatives you've considered**
Any set of complementary colors that work for 3 color (believe we only have 3 structure elements), such as found through a resource[ like this one](https://davidmathlogic.com/colorblind/#%23648FFF-%23785EF0-%23DC267F-%23FE6100-%23FFB000)

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Determine that there are only 3 structure elements, if not, select new colors from the same palette
- [ ] Test the color selection on a record, like EGFR, that has plenty of secondary structure
- [ ] Test on UVA instance.
